---
apiVersion: v1
kind: Secret
metadata:
  name: git-ssh
  namespace: #@ data.values.tap.namespace
  annotations:
    tekton.dev/git-0: https://github.com
    kapp.k14s.io/change-rule.0: "delete after deleting tanzu-app-platform"
type: kubernetes.io/basic-auth
stringData:
  username: #@ data.values.tap.credentials.github.username
  password: #@ data.values.tap.credentials.github.token