#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:json", "json")
---
apiVersion: v1
kind: Secret
metadata:
  name: ns-provisioner
  namespace: #@ data.values.tap.namespace
  annotations:
    tekton.dev/git-0: https://github.com
    kapp.k14s.io/change-rule.0: "delete after deleting tanzu-app-platform"
type: kubernetes.io/basic-auth
stringData:
  username: #@ data.values.tap.credentials.github.username
  password: #@ data.values.tap.credentials.github.token

---
apiVersion: v1
kind: Secret
metadata:
  name: ns-provisioner-scan-policies
  namespace: #@ data.values.tap.namespace
  annotations:
    tekton.dev/git-0: https://github.com
    kapp.k14s.io/change-rule.0: "delete after deleting tanzu-app-platform"
type: kubernetes.io/basic-auth
stringData:
  username: #@ data.values.tap.credentials.github.username
  password: #@ data.values.tap.credentials.github.token