#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  annotations:
    kapp.k14s.io/change-rule: "upsert after upserting tap-configs"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email:  #@ data.values.tap.credentials.cluster_issuer.email
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
    - dns01:
        azureDNS:
          clientID: #@ data.values.tap.credentials.cluster_issuer.azure_app_id
          clientSecretSecretRef:
            name: azuredns-config
            key: client-secret
          subscriptionID: #@ data.values.tap.credentials.cluster_issuer.azure_subscription_id
          tenantID: #@ data.values.tap.credentials.cluster_issuer.azure_tenant_id
          resourceGroupName: #@ data.values.tap.credentials.cluster_issuer.azure_dns_zone_resource_group
          hostedZoneName: #@ data.values.tap.credentials.cluster_issuer.azure_dns_zone
          environment: AzurePublicCloud